"""add portfolio_value and active_companies to investors

Revision ID: 1e3d410605ce
Revises: 801cdfaa8c55
Create Date: 2026-05-14 11:32:05.296215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3d410605ce'
down_revision: Union[str, Sequence[str], None] = '801cdfaa8c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investors', sa.Column('portfolio_value', sa.Float(), nullable=True))
    op.add_column('investors', sa.Column('active_companies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investors', 'active_companies')
    op.drop_column('investors', 'portfolio_value')
    # ### end Alembic commands ###
