"""add notifications table

Revision ID: 801cdfaa8c55
Revises: 247c15cce712
Create Date: 2026-05-10 15:51:10.441142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801cdfaa8c55'
down_revision: Union[str, Sequence[str], None] = '247c15cce712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('investors', sa.Column('region_std', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('uq_talent_rec'), 'talent_recommendations', type_='unique')
    op.drop_column('users', 'age')
    op.drop_column('users', 'degree_level')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'field_of_study')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('field_of_study', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('degree_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_talent_rec'), 'talent_recommendations', ['job_id', 'talent_id', 'recommendation_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('investors', 'region_std')
    op.drop_table('notifications')
    # ### end Alembic commands ###
